### PR TITLE
Lumen 5.7

### PR DESCRIPTION
**Pull request by jamieburnip**
Just updating the composer file to allow use on `5.6` and `5.7`. Test ran and looks good.

### CODE REVIEW

**Review by dankuck — APPROVED** [review]
Looks good to me

**Comment by jamieburnip** [comment]
Who can merge?

**Comment by KarmicXKoala** [comment]
I'll contact someone with merge access tomorrow so we can get this out

**Comment by jamieburnip** [comment]
Hey guys, is it possible to nudge you for a updated release? :)

**Comment by bbene** [comment]
An updated release with this composer change would be great.

**Comment by dankuck** [comment]
I'm contacting someone at That's Us right now

**Comment by bbene** [comment]
> I'm contacting someone at That's Us right now

Just curious, does anybody at That's Us actively support this library? It seems odd that you have to contact somebody to create a new release (read, they don't monitor it), and also odd that this repo has the issues feature disabled.

**Pull request merged**
